services:

  db:
    image: mysql    
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    - "3360:3306"  
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8087:8080

volumes:
  mysql_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${DEVICE_PATH}"